# Generated by Django 3.1.6 on 2021-02-22 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cricanalysisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(choices=[('Male', 'Male'), ('Female', 'Female')], null=True)),
                ('gender', models.IntegerField(null=True)),
                ('photo', models.FileField(null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
