# Generated by Django 3.1.6 on 2021-02-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricanalysisapp', '0002_desig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desig',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='desig',
            name='gender',
            field=models.IntegerField(choices=[('Male', 'Male'), ('Female', 'Female')], null=True),
        ),
    ]
