# Generated by Django 3.1.6 on 2021-02-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricanalysisapp', '0004_auto_20210224_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desig',
            name='photo',
            field=models.FileField(null=True, upload_to='documentuser/'),
        ),
    ]
