# Generated by Django 3.1.6 on 2021-02-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricanalysisapp', '0005_auto_20210224_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desig',
            name='photo',
            field=models.ImageField(null=True, upload_to='poster/'),
        ),
    ]
